name: Deploy Lambda

on:

  workflow_dispatch:

jobs:
  terraform:
    name: Deploy Lambda With Terraform
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Initialize Terraform
      run: terraform init -chdir=terraform -backend-config=dev.tfbackend"

    # - name: Plan Terraform DEV
    #   run: |
    #     git config --get remote.origin.url
    #     repo_url=$(git config --get remote.origin.url)
    #     repo_name=$(basename -s .git "$repo_url")
    #     echo $repo_name
    #     terraform plan -var="github_repo=$repo_name" -out=devtfplan

    # - name: Apply Terraform DEV
    #   run: terraform apply devtfplan